using System;
using System.Collections.Generic;

namespace NewChangeReportGenerator.Core;

internal class MainSortingAlgorithm {
    private readonly List<string> _rowNumberList; //First row generated by Teamcenter, which contains ordinal number with hyperlink to SAP Material or Document
    private readonly List<string> _sapObjectList;
    private readonly List<string> _definedByList;

    public Dictionary<string, string>[] GetDefinedByItemsWithUrls() {
        List<string> splitedListOfDocuments = SplitListOfDocuments(_definedByList);
        Dictionary<string, string>[] definedByWithUrlsDictionaries = new Dictionary<string, string>[splitedListOfDocuments.Count];
        
        for (int i = 0; i < _definedByList.Count; i++) {
            foreach (string definedByItemName in splitedListOfDocuments) {
                for (int j = 0; j < _sapObjectList.Count; j++) {
                    if (_sapObjectList[j].Contains(definedByItemName)) {
                        definedByWithUrlsDictionaries[j].Add(definedByItemName, _rowNumberList[j]);
                    }
                }
            }
        }
        return definedByWithUrlsDictionaries;
    }

    private List<string> SplitListOfDocuments(List<string> inputList) {
        List<string> outputList = new List<string>();

        foreach (var inputString in inputList) {
            string[] splittedStrings = inputString.Split(", D", StringSplitOptions.TrimEntries);

            foreach (string splittedString in splittedStrings) {
                outputList.Add(splittedString);
            }
        }

        return outputList;
    }

    public MainSortingAlgorithm(List<string> rowNumberList, List<string> sapObjectList, List<string> definedByList) {
        _rowNumberList = rowNumberList;
        _sapObjectList = sapObjectList;
        _definedByList = definedByList;
    }
}