using System.Collections.Generic;

namespace ChangeNotificationGenerator.Core;

internal class MainSortingAlgorithm {
    private readonly List<string> _rowNumberList; //First row generated by Teamcenter, which contains ordinal number with hyperlink to SAP Material or Document
    private readonly List<string> _sapObjectList;
    private readonly List<string> _definedByList;

    private string[] SplitListItemToArray(string itemToSplit) {
        return itemToSplit.Split(", D");
    }

    private Dictionary<string, string> AssignDefinedByItemToUrl(string[] splittedStringsArray) {
        var returnedDictionary = new Dictionary<string, string>();

        foreach (var item in splittedStringsArray) {
            int sapObjectListIndex = FindDefinedByItemIndexInSapObjectList(item);
            returnedDictionary.Add(item, _rowNumberList[sapObjectListIndex]);
        }

        return returnedDictionary;
    }

    public List<Dictionary<string, string>> DefinedByItemsWithUrls() {
        List<Dictionary<string, string>> returnedDictionariesList = new List<Dictionary<string, string>>();

        for (int i = 0; i < _sapObjectList.Count; i++) {
            if (_sapObjectList[i].Contains("ENE-Part")) {
                if (string.IsNullOrEmpty(_definedByList[i]) || string.IsNullOrWhiteSpace(_definedByList[i])) continue;

                string[] splittedDocumentsArray = SplitListItemToArray(_definedByList[i]);
                Dictionary<string, string> definedByDictionary = AssignDefinedByItemToUrl(splittedDocumentsArray);

                returnedDictionariesList.Add(definedByDictionary);
            }
        }
        return returnedDictionariesList;
    }
    public int FindDefinedByItemIndexInSapObjectList(string definedByItemName) {
        int foundInteger = 0;
        
        for (int j = 0; j < _sapObjectList.Count; j++) {
            if (_sapObjectList[j].Contains(definedByItemName)) {
                foundInteger = j;
                break;
            }
        }
        return foundInteger;
    }
    


    public MainSortingAlgorithm(List<string> rowNumberList, List<string> sapObjectList, List<string> definedByList) {
        _rowNumberList = rowNumberList;
        _sapObjectList = sapObjectList;
        _definedByList = definedByList;
    }
}