using System;
using System.Collections.Generic;
using System.Linq;

namespace NewChangeReportGenerator.Core;

internal class MainSortingAlgorithm {
    private readonly List<string> _rowNumberList; //First row generated by Teamcenter, which contains ordinal number with hyperlink to SAP Material or Document
    private readonly List<string> _sapObjectList;
    private readonly List<string> _definedByList;

    public Dictionary<string, string>[] GetDefinedByItemsWithUrls() {
        List<string> splittedListOfDocuments = SplitListOfDocuments(_definedByList);
        Dictionary<string, string>[] definedByWithUrlsDictionaries = new Dictionary<string, string>[_sapObjectList.Count];
        
        for (int i = 0; i < _definedByList.Count; i++) {
            foreach (string definedByItemName in splittedListOfDocuments) {

                if (definedByItemName.Contains("Defined By")) { continue; }

                Dictionary<string, string> definedByItemWithUrl = new Dictionary<string, string>();
                int definedByWithUrlIndex = FindDefinedByItemIndexInSapObjectList(definedByItemName);

                definedByItemWithUrl.Add(definedByItemName, _rowNumberList[definedByWithUrlIndex]);
                definedByWithUrlsDictionaries[definedByWithUrlIndex] = definedByItemWithUrl;
            }
        }
        return definedByWithUrlsDictionaries;
    }

    public int FindDefinedByItemIndexInSapObjectList(string definedByItemName) {
        int foundInteger = 0;
        
        for (int j = 0; j < _sapObjectList.Count; j++) {
            if (_sapObjectList[j].Contains(definedByItemName)) {
                foundInteger = j;
                break;
            }
        }
        return foundInteger;
    }
    
    private List<string> SplitListOfDocuments(List<string> inputList) {
        List<string> outputList = new List<string>();

        foreach (var inputString in inputList) {
            if (string.IsNullOrEmpty(inputString)) continue;
            List<string> splittedStrings = inputString.Split(", D", StringSplitOptions.TrimEntries).ToList();

            if (splittedStrings.Count > 1) {
                splittedStrings.ForEach(splittedString => outputList.Add(splittedString));
            } else {
                outputList.Add(inputString);
            }
        }
        return outputList;
    }

    public MainSortingAlgorithm(List<string> rowNumberList, List<string> sapObjectList, List<string> definedByList) {
        _rowNumberList = rowNumberList;
        _sapObjectList = sapObjectList;
        _definedByList = definedByList;
    }
}